export default [
	{
		firstName: "Mohamed",
		lastName: "Salah",
		position: ["Forward"],
		height: "5'9\"",
		weight: "157 lbs",
		age: 28,
		strongFoot: "Left",
		price: {
			type: "Exact",
			value: "$150 million",
		},
		email: "m.sal@liverpoolfc.com",
		currentClub: "Liverpool FC",
		availability: "Not available",
		bio: 'Mohamed Salah is an Egyptian professional footballer who plays as a forward for Liverpool and the Egypt national team. Salah has been described as a "prolific scorer" and "a game-changer" who is known for his finishing, dribbling, and speed.',
		location: "Liverpool, United Kingdom",
		hometown: "Nagrig, Egypt",
		gender: "Male",
		language: "Arabic, English",
		imageSrc: "/src/assets/player1.webp",
	},
	{
		firstName: "Sadio",
		lastName: "Mané",
		position: ["Forward"],
		height: "5'9\"",
		weight: "157 lbs",
		age: 29,
		strongFoot: "Left",
		price: {
			type: "Exact",
			value: "$150 million",
		},
		email: "s.mane@liverpoolfc.com",
		currentClub: "Liverpool FC",
		availability: "Not available",
		bio: "Sadio Mané is a Senegalese professional footballer who plays as a forward for Liverpool and the Senegal national team. Mané is widely regarded as one of the best wingers in the world, and has been praised for his pace, work rate, and finishing ability.",
		location: "Liverpool, United Kingdom",
		hometown: "Bambali, Senegal",
		gender: "Male",
		language: "Wolof, French, English",
		imageSrc: "/src/assets/player2.webp",
	},
	{
		firstName: "Riyad",
		lastName: "Mahrez",
		position: ["Forward", "Midfielder"],
		height: "5'10\"",
		weight: "148 lbs",
		age: 30,
		strongFoot: "Left",
		price: {
			type: "Exact",
			value: "$50 million",
		},
		email: "riyad.mahrez@mancity.com",
		currentClub: "Manchester City FC",
		availability: "Available",
		bio: "Riyad Mahrez is an Algerian professional footballer who plays as a winger for Manchester City and the Algeria national team. Mahrez is known for his dribbling skills, ability to score from free kicks, and precise passing.",
		location: "Manchester, United Kingdom",
		hometown: "Sarcelles, France",
		gender: "Male",
		language: "Arabic, French, English",
		imageSrc: "/src/assets/player3.webp",
	},
	{
		firstName: "Serge",
		lastName: "Aurier",
		position: ["Defender"],
		height: "5'10\"",
		weight: "168 lbs",
		age: 28,
		strongFoot: "Right",
		price: {
			type: "Exact",
			value: "$20 million",
		},
		email: "s.aurier@spurs.com",
		currentClub: "Tottenham Hotspur FC",
		availability: "Available",
		bio: "Serge Aurier is an Ivorian professional footballer who plays as a right-back for Tottenham Hotspur and the Ivory Coast national team. Aurier is known for his speed, stamina, and aggressive playing style.",
		location: "London, United Kingdom",
		hometown: "Ouégnin, Ivory Coast",
		gender: "Male",
		language: "French, English",
		imageSrc: "/src/assets/player1.webp",
	},
	{
		firstName: "Cristiano",
		lastName: "Ronaldo",
		position: ["Forward", "Winger"],
		height: "6'2\"",
		weight: "183 lbs",
		age: 36,
		strongFoot: "Right",
		price: {
			type: "Exact",
			value: "$100 million",
		},
		email: "c.ronaldo@juventus.com",
		currentClub: "Juventus FC",
		availability: "Available for transfer",
		bio: "Cristiano Ronaldo is a Portuguese professional footballer who plays as a forward for Juventus and the Portugal national team. Ronaldo is considered one of the greatest footballers of all time and is known for his speed, dribbling skills, and goal-scoring abilities.",
		location: "Turin, Italy",
		hometown: "Funchal, Portugal",
		gender: "Male",
		language: "Portuguese, English, Spanish",
		imageSrc: "/src/assets/player1.webp",
	},
	{
		firstName: "Lionel",
		lastName: "Messi",
		position: ["Forward", "Attacking midfielder"],
		height: "5'7\"",
		weight: "148 lbs",
		age: 34,
		strongFoot: "Left",
		price: {
			type: "Exact",
			value: "$150 million",
		},
		email: "l.messi@psg.com",
		currentClub: "Paris Saint-Germain FC",
		availability: "Not available for transfer",
		bio: "Lionel Messi is an Argentine professional footballer who plays as a forward for Paris Saint-Germain and the Argentina national team. Messi is considered one of the greatest footballers of all time and is known for his dribbling skills, vision, and goal-scoring abilities.",
		location: "Paris, France",
		hometown: "Rosario, Argentina",
		gender: "Male",
		language: "Spanish, Catalan, English",
		imageSrc: "/src/assets/player1.webp",
	},
	{
		firstName: "Emma",
		lastName: "Johnson",
		position: ["Midfielder"],
		height: "5'8\"",
		weight: "145 lbs",
		age: 24,
		strongFoot: "Left",
		price: {
			type: "Exact",
			value: "$10 million",
		},
		email: "emma.johnson@gmail.com",
		currentClub: "FC Barcelona",
		availability: "Available for transfer",
		bio: "Emma Johnson is a young and talented midfielder known for her excellent dribbling and passing abilities. She is a key player for her team and is highly sought after by top clubs around the world.",
		location: "Barcelona, Spain",
		hometown: "Madrid, Spain",
		gender: "Female",
		language: "Spanish, English",
		imageSrc: "/src/assets/player1.webp",
	},
	{
		firstName: "James",
		lastName: "Roberts",
		position: ["Defender"],
		height: "6'2\"",
		weight: "175 lbs",
		age: 29,
		strongFoot: "Right",
		price: {
			type: "Negotiable",
			value: "$8 million",
		},
		email: "james.roberts@gmail.com",
		currentClub: "AC Milan",
		availability: "Available for transfer",
		bio: "James Roberts is a strong and reliable defender with a great sense of positioning and aerial ability. He is a consistent performer for his team and is looking to make a move to a bigger club to further his career.",
		location: "Milan, Italy",
		hometown: "Manchester, United Kingdom",
		gender: "Male",
		language: "English, Italian",
		imageSrc: "/src/assets/player1.webp",
	},
	{
		firstName: "Maria",
		lastName: "Garcia",
		position: ["Forward"],
		height: "5'6\"",
		weight: "135 lbs",
		age: 27,
		strongFoot: "Right",
		price: {
			type: "Exact",
			value: "$15 million",
		},
		email: "maria.garcia@gmail.com",
		currentClub: "Real Madrid",
		availability: "Not available for transfer",
		bio: "Maria Garcia is a pacey and skillful forward with an eye for goal. She is a crucial player for Real Madrid and has been a consistent performer for her team over the years.",
		location: "Madrid, Spain",
		hometown: "Barcelona, Spain",
		gender: "Female",
		language: "Spanish, Catalan, English",
		imageSrc: "/src/assets/player1.webp",
	},
	{
		firstName: "Serge",
		lastName: "Aurier",
		position: ["Defender"],
		height: "5'10\"",
		weight: "168 lbs",
		age: 28,
		strongFoot: "Right",
		price: {
			type: "Exact",
			value: "$20 million",
		},
		email: "s.aurier@spurs.com",
		currentClub: "Tottenham Hotspur FC",
		availability: "Available",
		bio: "Serge Aurier is an Ivorian professional footballer who plays as a right-back for Tottenham Hotspur and the Ivory Coast national team. Aurier is known for his speed, stamina, and aggressive playing style.",
		location: "London, United Kingdom",
		hometown: "Ouégnin, Ivory Coast",
		gender: "Male",
		language: "French, English",
		imageSrc: "/src/assets/player1.webp",
	},
	{
		firstName: "Neymar",
		lastName: "Jr.",
		position: ["Forward", "Winger"],
		height: "5'9\"",
		weight: "150 lbs",
		age: 30,
		strongFoot: "Right",
		price: {
			type: "Exact",
			value: "$180 million",
		},
		email: "neymar@psg.com",
		currentClub: "Paris Saint-Germain FC",
		availability: "Not available for transfer",
		bio: "Neymar Jr. is a Brazilian professional footballer who plays as a forward for Paris Saint-Germain and the Brazil national team. Neymar is known for his dribbling skills, creativity, and ability to score goals.",
		location: "Paris, France",
		hometown: "Mogi das Cruzes, Brazil",
		gender: "Male",
		language: "Portuguese, Spanish, English",
		imageSrc: "/src/assets/player1.webp",
	},
	{
		firstName: "Erling",
		lastName: "Haaland",
		position: ["Forward"],
		height: "6'4\"",
		weight: "193 lbs",
		age: 21,
		strongFoot: "Right",
		price: {
			type: "Exact",
			value: "$150 million",
		},
		email: "e.haaland@bvb.de",
		currentClub: "Borussia Dortmund",
		availability: "Available for transfer",
		bio: "Erling Haaland is a Norwegian professional footballer who plays as a forward for Borussia Dortmund and the Norway national team. Haaland is known for his physical strength, pace, and clinical finishing ability.",
		location: "Dortmund, Germany",
		hometown: "Bryne, Norway",
		gender: "Male",
		language: "Norwegian, English, German",
		imageSrc: "/src/assets/player1.webp",
	},
];
